// Course mapping data with course codes and names
export const courseMapping = [
  // First Semester Courses
  { courseNumber: 'MA11001', courseName: 'Differential Equations and Linear Algebra' },
  { courseNumber: 'CH10001', courseName: 'Chemistry' },
  { courseNumber: 'HS10001', courseName: 'English' },
  { courseNumber: 'EC10001', courseName: 'Basic Electronics' },
  { courseNumber: 'CH19001', courseName: 'Chemistry Lab' },
  { courseNumber: 'EX19001', courseName: 'Engineering Lab' },
  { courseNumber: 'ME18001', courseName: 'Workshop' },
  { courseNumber: 'HS18001', courseName: 'Communication Lab' },
  { courseNumber: 'YG18001', courseName: 'Yoga' },
  { courseNumber: 'EE10002', courseName: 'Basic Electrical Engineering' },
  { courseNumber: 'SO10043', courseName: 'Socio-Political Environment' },
    // Second Semester Courses
  { courseNumber: 'MA11002', courseName: 'Transforms and Numerical Methods' },
  { courseNumber: 'PH10001', courseName: 'Physics' },
  { courseNumber: 'LS10001', courseName: 'Science of living Systems' },
  { courseNumber: 'CH10003', courseName: 'Environmental Science' },
  { courseNumber: 'PH19001', courseName: 'Physics Lab' },
  { courseNumber: 'CS13001', courseName: 'Programming Lab' },
  { courseNumber: 'CE18001', courseName: 'Engineering Drawing and Graphics' },
  { courseNumber: 'EC10003', courseName: 'Biomedical Engineering' },
  { courseNumber: 'PH10003', courseName: 'Smart Materials' },
    // Third Semester Courses
  { courseNumber: 'MA21001', courseName: 'Probability and Statistics' },
  { courseNumber: 'EX20001', courseName: 'Industry 4.0 Technologies' },
  { courseNumber: 'CS21001', courseName: 'Data Structures' },
  { courseNumber: 'EC20005', courseName: 'Digital Systems Design' },
  { courseNumber: 'CS21003', courseName: 'Automata Theory and Formal Languages' },
  { courseNumber: 'CS29001', courseName: 'Data Structures Laboratory' },
  { courseNumber: 'EC29005', courseName: 'Digital Systems Design Laboratory' },
  { courseNumber: 'HS20120', courseName: 'Economics of Development' },
  
  // Fourth Semester Courses
  { courseNumber: 'EX20003', courseName: 'Scientific and Technical Writing' },
  { courseNumber: 'MA21002', courseName: 'Discrete Mathematics' },
  { courseNumber: 'CE28004', courseName: 'Computer aided Building Drawing' },
  
  // Existing courses
  { courseNumber: 'HS30401', courseName: 'Universal Human Values' },
  { courseNumber: 'CS30002', courseName: 'Artificial Intelligence' },
  { courseNumber: 'CS31002', courseName: 'Machine Learning' },
  { courseNumber: 'CS39002', courseName: 'Artificial Intelligence Laboratory' },
  { courseNumber: 'CS33002', courseName: 'Applications Development Laboratory' },
  { courseNumber: 'CS37001', courseName: 'Mini Project' },
  { courseNumber: 'CS30010', courseName: 'Cloud Computing' },
  { courseNumber: 'HS30225', courseName: 'Leadership and Team Effectiveness' },
  { courseNumber: 'OC30001', courseName: 'Business Ethics and Corporate Governance' },
  { courseNumber: 'CS20002', courseName: 'Operating Systems' },
  { courseNumber: 'CS20004', courseName: 'Object Oriented Programming using Java' },
  { courseNumber: 'CS20006', courseName: 'Database Management Systems' },
  { courseNumber: 'CS21002', courseName: 'Computer Organization and Architecture' },
  { courseNumber: 'CS29002', courseName: 'Operating Systems Laboratory' },
  { courseNumber: 'CS29004', courseName: 'Object Oriented Programming Laboratory' },
  { courseNumber: 'CS29006', courseName: 'Database Management Systems Laboratory' },
  { courseNumber: 'CS40078', courseName: 'Deep Learning' },
  { courseNumber: 'CS40032', courseName: 'Parallel and Distributed Systems' },
  { courseNumber: 'CS40098', courseName: 'Blockchain and Cryptocurrency' },
  { courseNumber: 'CS40032', courseName: 'Computer Vision' },
  { courseNumber: 'HS40003', courseName: 'Professional Communication' },
  { courseNumber: 'CS30001', courseName: 'Theory of Computation' },
  { courseNumber: 'CS30003', courseName: 'Compiler Design' },
  { courseNumber: 'CS30005', courseName: 'Algorithms' },
  { courseNumber: 'CS40002', courseName: 'Big Data Processing' },
  { courseNumber: 'CS40042', courseName: 'Natural Language Processing' },
  { courseNumber: 'CS21008', courseName: 'Discrete Mathematics' },
  { courseNumber: 'MA20015', courseName: 'Probability and Statistics' },
  { courseNumber: 'MA20021', courseName: 'Linear Algebra' },
  { courseNumber: 'MA20013', courseName: 'Differential Equations' },
  { courseNumber: 'CS30018', courseName: 'Software Engineering' },
  { courseNumber: 'CE1081', courseName: 'Engg. Graphics' },
  { courseNumber: 'CE1082', courseName: 'Estimating & Costing' },
  { courseNumber: 'CE1083', courseName: 'Structural Design (Steel)' },
  { courseNumber: 'CE1084', courseName: 'Structural Design (RCC)' },
  { courseNumber: 'CE1085', courseName: 'Hydrologic Design' },
  { courseNumber: 'CE1086', courseName: 'Geotechnical Engineering Design' },
  { courseNumber: 'CE1087', courseName: 'Transportation Design' },
  { courseNumber: 'CE1091', courseName: 'Environmental Engg. Lab.' },
  { courseNumber: 'CE1092', courseName: 'Fluid Mechanics Lab' },
  { courseNumber: 'CE1093', courseName: 'Material Testing Lab.' },
  { courseNumber: 'CE1094', courseName: 'Transportation Engg. Lab.' },
  { courseNumber: 'CE1098', courseName: 'Surveying Field Work' },
  { courseNumber: 'CE2003', courseName: 'Solid Mechanics' },
  { courseNumber: 'CE2004', courseName: 'Structural Analysis-I' },
  { courseNumber: 'CE2005', courseName: 'Surveying' },
  { courseNumber: 'CE2007', courseName: 'Civil Engineering Materials & Construction' },
  { courseNumber: 'CE2008', courseName: 'Advanced Surveying' },
  { courseNumber: 'CE2011', courseName: 'Fluid Mechanics-I' },
  { courseNumber: 'CE2014', courseName: 'Fluid Mechanics-II' },
  { courseNumber: 'CE2016', courseName: 'Transportation Engineering' },
  { courseNumber: 'CE2018', courseName: 'Design of Concrete Structure-I' },
  { courseNumber: 'CE2019', courseName: 'Environmental Engineering-I' },
  { courseNumber: 'CE2081', courseName: 'Building Drawing' },
  { courseNumber: 'CE2082', courseName: 'Estimating & Costing' },
  { courseNumber: 'CE2084', courseName: 'Structural Design (RCC)' },
  { courseNumber: 'CE2088', courseName: 'Water Resources Design' },
  { courseNumber: 'CE2091', courseName: 'Environmental Engg. Lab.' },
  { courseNumber: 'CE2092', courseName: 'Fluid Mechanics Lab' },
  { courseNumber: 'CE2093', courseName: 'Material Testing Lab.' },
  { courseNumber: 'CE2094', courseName: 'Transportation Engg. Lab.' },
  { courseNumber: 'CE2098', courseName: 'Surveying Field Work' },
  { courseNumber: 'CE3001', courseName: 'Structural Analysis-II' },
  { courseNumber: 'CE3006', courseName: 'Design of Concrete Structures-II' },
  { courseNumber: 'CE3007', courseName: 'Design of Steel Structure' },
  { courseNumber: 'CE3008', courseName: 'Environmental Engineering-II' },
  { courseNumber: 'CE3009', courseName: 'Water Resources Engineering-I' },
  { courseNumber: 'CE3010', courseName: 'Water Resources Engineering-II' },
  { courseNumber: 'CE3011', courseName: 'Geotechnical Engineering-I' },
  { courseNumber: 'CE3013', courseName: 'Construction Planning & Management' },
  { courseNumber: 'CE3014', courseName: 'Geotechnical Engineering-II' },
  { courseNumber: 'CE3021', courseName: 'Advanced Solid Mechanics' },
  { courseNumber: 'CE3023', courseName: 'Concrete Technology' },
  { courseNumber: 'CE3027', courseName: 'Engineering Geology' },
  { courseNumber: 'CE3029', courseName: 'Environmental Impact Assessment & Auditing' },
  { courseNumber: 'CE3031', courseName: 'Railways Engineering' },
  { courseNumber: 'CE3033', courseName: 'Groundwater Hydrology' },
  { courseNumber: 'CE3035', courseName: 'Hydraulic Machines' },
  { courseNumber: 'CE3037', courseName: 'Pavement Analysis & Design' },
  { courseNumber: 'CE3039', courseName: 'Pavement Materials' },
  { courseNumber: 'CE3041', courseName: 'Traffic Engineering & Transportation Planning' },
  { courseNumber: 'CE3082', courseName: 'Minor Project' },
  { courseNumber: 'CE3083', courseName: 'Structural Design (Steel)' },
  { courseNumber: 'CE3084', courseName: 'Structural Design (RCC)' },
  { courseNumber: 'CE3085', courseName: 'Hydrologic Design' },
  { courseNumber: 'CE3086', courseName: 'Geotechnical Engineering Design' },
  { courseNumber: 'CE3087', courseName: 'Transportation Design' },
  { courseNumber: 'CE3088', courseName: 'Water Resources Design' },
  { courseNumber: 'CE3091', courseName: 'Geotechnical Engineering Lab' },
  { courseNumber: 'CE3092', courseName: 'Concrete & Structure Lab.' },
  { courseNumber: 'CE3093', courseName: 'Material Testing Lab.' },
  { courseNumber: 'CE3094', courseName: 'Transportation Engg. Lab.' },
  { courseNumber: 'CE3098', courseName: 'Surveying Field Work' },
  { courseNumber: 'CE4020', courseName: 'Pavement Management System' },
  { courseNumber: 'CE4027', courseName: 'Advanced Steel Design' },
  { courseNumber: 'CE4029', courseName: 'Disaster Management' },
  { courseNumber: 'CE4033', courseName: 'Structural Dynamics' },
  { courseNumber: 'CE4051', courseName: 'Flood and Drought Estimation and Management' },
  { courseNumber: 'CE4053', courseName: 'Solid and Hazardous Waste Management' },
  { courseNumber: 'CE4057', courseName: 'Drainage Engineering & Design' },
  { courseNumber: 'CE4059', courseName: 'Reinforced Concrete Repairs and Maintenance' },
  { courseNumber: 'CE4061', courseName: 'Earthquake Engineering' },
  { courseNumber: 'CE4062', courseName: 'Water Resources System Analysis' },
  { courseNumber: 'CE4063', courseName: 'Finite Element Method in Geo-mechanics' },
  { courseNumber: 'CE4065', courseName: 'Infrastructure Planning' },
  { courseNumber: 'CE4067', courseName: 'Offshore Geotechnical Engineering' },
  { courseNumber: 'CE4069', courseName: 'Cost Effective Housing' },
  { courseNumber: 'CE4077', courseName: 'Earth & Earth Retaining Structures' },
  { courseNumber: 'CE4081', courseName: 'Project Preparation' },
  { courseNumber: 'CE4082', courseName: 'Project' },
  { courseNumber: 'CE4083', courseName: 'Practical Training' },
  { courseNumber: 'CE4084', courseName: 'Seminar' },
  { courseNumber: 'CE4086', courseName: 'General Viva-Voce' },
  { courseNumber: 'CE4100', courseName: 'Capstone Project' },
  { courseNumber: 'CE6102', courseName: 'Construction Engineering Practices' },
  { courseNumber: 'CE6103', courseName: 'Construction Finance Management' },
  { courseNumber: 'CE6105', courseName: 'Pre-stressed Concrete' },
  { courseNumber: 'CE6136', courseName: 'Building Services Planning' },
  { courseNumber: 'CE6138', courseName: 'Advanced Repairs and Rehabilitation of Structures' },
  { courseNumber: 'CE6142', courseName: 'Contract Laws & Regulations' },
  { courseNumber: 'CE6206', courseName: 'Finite Element Method' },
  { courseNumber: 'CS1001', courseName: 'Programming in C' },
  { courseNumber: 'CS1091', courseName: 'Programming Lab in C' },
  { courseNumber: 'CS2001', courseName: 'Data Structures & Algorithms' },
  { courseNumber: 'CS2004', courseName: 'Database Management Systems' },
  { courseNumber: 'CS2006', courseName: 'Computer Organization and Architecture' },
  { courseNumber: 'CS2008', courseName: 'Design & Analysis of Algorithms' },
  { courseNumber: 'CS2091', courseName: 'Data Structures Lab' },
  { courseNumber: 'CS2094', courseName: 'DBMS Lab' },
  { courseNumber: 'CS2096', courseName: 'Design & Analysis of Algorithms Lab' },
  { courseNumber: 'CS2098', courseName: 'COA Lab' },
  { courseNumber: 'CS3002', courseName: 'Compiler Design' },
  { courseNumber: 'CS3003', courseName: 'Formal Languages and Automata Theory' },
  { courseNumber: 'CS3004', courseName: 'Computer Graphics' },
  { courseNumber: 'CS3007', courseName: 'High Performance Computer Architecture' },
  { courseNumber: 'CS3009', courseName: 'Operating Systems' },
  { courseNumber: 'CS3022', courseName: 'Parallel and Distributed Computing' },
  { courseNumber: 'CS3024', courseName: 'Distributed Operating Systems' },
  { courseNumber: 'CS3026', courseName: 'Distributed Database Systems' },
  { courseNumber: 'CS3028', courseName: 'Artificial Intelligence' },
  { courseNumber: 'CS3030', courseName: 'Computational Intelligence' },
  { courseNumber: 'CS3032', courseName: 'Big Data' },
  { courseNumber: 'CS3034', courseName: 'Service Oriented Architecture' },
  { courseNumber: 'CS3037', courseName: 'Human Computer Interaction' },
  { courseNumber: 'CS3046', courseName: 'Introduction to Computer Graphics' },
  { courseNumber: 'CS3082', courseName: 'Minor Project' },
  { courseNumber: 'CS3091', courseName: 'Operating Systems Laboratory' },
  { courseNumber: 'CS3092', courseName: 'Compiler Design Laboratory' },
  { courseNumber: 'CS3093', courseName: 'Tools and Techniques Lab' },
  { courseNumber: 'CS3094', courseName: 'Computer Graphics Laboratory' },
  { courseNumber: 'CS3095', courseName: 'Advanced Programming Lab' },
  { courseNumber: 'CS4003', courseName: 'Legal Issues & Requirement in Engineering' },
  { courseNumber: 'CS4025', courseName: 'Microprocessor' },
  { courseNumber: 'CS4027', courseName: 'Real-time Systems' },
  { courseNumber: 'CS4029', courseName: 'Embedded System' },
  { courseNumber: 'CS4031', courseName: 'Software Testing' },
  { courseNumber: 'CS4037', courseName: 'Human Computer Interaction' },
  { courseNumber: 'CS4081', courseName: 'Project (Part-I)' },
  { courseNumber: 'CS4082', courseName: 'Project (Part-II)' },
  { courseNumber: 'CS4083', courseName: 'Practical Training' },
  { courseNumber: 'CS4084', courseName: 'Seminar' },
  { courseNumber: 'CS4086', courseName: 'General Viva Voce' },
  { courseNumber: 'EC1001', courseName: 'Basic Electronics' },
  { courseNumber: 'EC1091', courseName: 'Basic Electronics Lab' },
  { courseNumber: 'EC2003', courseName: 'Signals & Systems' },
  { courseNumber: 'EC2004', courseName: 'Principle of Digital Communication' },
  { courseNumber: 'EC2011', courseName: 'Digital Electronics' },
  { courseNumber: 'EC2015', courseName: 'Analog Circuits' },
  { courseNumber: 'EC2016', courseName: 'Communication Engineering' },
  { courseNumber: 'EC2093', courseName: 'Digital Electronics Lab' },
  { courseNumber: 'EC2094', courseName: 'Communication Engineering Lab' },
  { courseNumber: 'EC3003', courseName: 'Microprocessors & Microcontrollers' },
  { courseNumber: 'EC3007', courseName: 'Digital Signal Processing' },
  { courseNumber: 'EC3011', courseName: 'VLSI Design' },
  { courseNumber: 'EC3012', courseName: 'Antenna & Radio Wave Propagation' },
  { courseNumber: 'EC3022', courseName: 'Advanced Microprocessors' },
  { courseNumber: 'EC3024', courseName: 'Embedded Systems' },
  { courseNumber: 'EC3025', courseName: 'Computational Intelligence' },
  { courseNumber: 'EC3027', courseName: 'Optical and Satellite Communication' },
  { courseNumber: 'EC3028', courseName: 'Data Communication and Networking' },
  { courseNumber: 'EC3030', courseName: 'Adaptive Systems and Signal Processing' },
  { courseNumber: 'EC3034', courseName: 'Industrial Data Networks' },
  { courseNumber: 'EC3093', courseName: 'Microprocessor and Microcontroller Lab' },
  { courseNumber: 'EC3095', courseName: 'VLSI Lab' },
  { courseNumber: 'EC3096', courseName: 'DSP Lab' },
  { courseNumber: 'EC4001', courseName: 'RF and Microwave Engineering' },
  { courseNumber: 'EC4003', courseName: 'Wireless and Mobile Communication' },
  { courseNumber: 'EC4031', courseName: 'Mobile Communication Engineering' },
  { courseNumber: 'EC4033', courseName: 'Smart Antennas' },
  { courseNumber: 'EC4044', courseName: 'Information Theory & Coding' },
  { courseNumber: 'EC4046', courseName: 'Modern Digital Communication' },
  { courseNumber: 'EC4081', courseName: 'Project (Part-I)' },
  { courseNumber: 'EC4082', courseName: 'Project (Part-II)' },
  { courseNumber: 'EC4083', courseName: 'Practical Training' },
  { courseNumber: 'EC4084', courseName: 'Seminar' },
  { courseNumber: 'EC4086', courseName: 'General Viva Voce' },
  { courseNumber: 'EC4091', courseName: 'Microwave and Antenna Lab' },
  { courseNumber: 'EC4093', courseName: 'Wireless Communication and Networking Lab' },
  { courseNumber: 'EC6102', courseName: 'Telecommunication Switching Networks and Protocols' },
  { courseNumber: 'EC6108', courseName: 'Digital Image Processing' },
  { courseNumber: 'EC6112', courseName: 'Communication and Network Security' },
  { courseNumber: 'EC6128', courseName: 'Wireless Sensor Networks' },
  { courseNumber: 'EC6224', courseName: 'Low Power VLSI Design' },
  { courseNumber: 'EC6316', courseName: 'Microwave Integrated Circuits' },
  { courseNumber: 'EE1003', courseName: 'Basic Electrical Engineering' },
  { courseNumber: 'EE1093', courseName: 'Basic Electrical Engineering Lab' },
  { courseNumber: 'EE2003', courseName: 'Network Analysis' },
  { courseNumber: 'EE2005', courseName: 'DC Machines and Transformers' },
  { courseNumber: 'EE2010', courseName: 'AC Machines' },
  { courseNumber: 'EE2012', courseName: 'Linear Control Theory' },
  { courseNumber: 'EE2014', courseName: 'Electromagnetics' },
  { courseNumber: 'EE2016', courseName: 'Electrical Measurements and Measuring Instruments' },
  { courseNumber: 'EE2091', courseName: 'Networks and Electronics Circuit Lab' },
  { courseNumber: 'EE2092', courseName: 'Electrical Measurements Lab' },
  { courseNumber: 'EE2094', courseName: 'Digital Circuit Lab' },
  { courseNumber: 'EE2096', courseName: 'Electrical Machines Lab' },
  { courseNumber: 'EE3002', courseName: 'Power System Operation and Control' },
  { courseNumber: 'EE3005', courseName: 'Power Electronics' },
  { courseNumber: 'EE3006', courseName: 'Electric Drives and Control' },
  { courseNumber: 'EE3007', courseName: 'Power Transmission and Distribution' },
  { courseNumber: 'EE3021', courseName: 'Principles of Industrial Instrumentation' },
  { courseNumber: 'EE3023', courseName: 'High Voltage Engineering' },
  { courseNumber: 'EE3025', courseName: 'Power Station Engineering' },
  { courseNumber: 'EE3027', courseName: 'Electrical Engineering Materials' },
  { courseNumber: 'EE3032', courseName: 'EHV AC Transmission' },
  { courseNumber: 'EE3034', courseName: 'Neural Network, Fuzzy Logic and Evolutionary Algorithm' },
  { courseNumber: 'EE3036', courseName: 'Discrete and Non linear Control Theory' },
  { courseNumber: 'EE3038', courseName: 'Utilization of Electric Power' },
  { courseNumber: 'EE3082', courseName: 'Minor Project' },
  { courseNumber: 'EE3091', courseName: 'Power Electronics Lab' },
  { courseNumber: 'EE3092', courseName: 'Power Systems Lab' },
  { courseNumber: 'EE3093', courseName: 'Microprocessor Lab' },
  { courseNumber: 'EE3094', courseName: 'Electric Drives Lab' },
  { courseNumber: 'EE4022', courseName: 'Bio Power' },
  { courseNumber: 'EE4024', courseName: 'Wind Power' },
  { courseNumber: 'EE4025', courseName: 'Electric Traction and Drive' },
  { courseNumber: 'EE4026', courseName: 'Solar Power' },
  { courseNumber: 'EE4028', courseName: 'Surge and Lightning Protection and Safety Devices' },
  { courseNumber: 'EE4029', courseName: 'HVDC Transmission' },
  { courseNumber: 'EE4031', courseName: 'Numerical Relays' },
  { courseNumber: 'EE4037', courseName: 'Advanced Power Electronics' },
  { courseNumber: 'EE4039', courseName: 'Power Quality' },
  { courseNumber: 'EE4081', courseName: 'Project (Part-I)' },
  { courseNumber: 'EE4082', courseName: 'Project (Part-II)' },
  { courseNumber: 'EE4083', courseName: 'Practical Training' },
  { courseNumber: 'EE4084', courseName: 'Seminar' },
  { courseNumber: 'EE4086', courseName: 'General Viva Voce' },
  { courseNumber: 'EE4087', courseName: 'Electrical Machine Design' },
  { courseNumber: 'EE4089', courseName: 'Electrical System Modeling and Simulation' },
  { courseNumber: 'EE6121', courseName: 'Computer Application in Power System' },
  { courseNumber: 'EE6123', courseName: 'Power Market Reforms' },
  { courseNumber: 'EE6336', courseName: 'Smart Grid' },
  { courseNumber: 'EL3001', courseName: 'Control Systems' },
  { courseNumber: 'EL3022', courseName: 'Advanced Control Systems' },
  { courseNumber: 'EL3024', courseName: 'Industrial Automation and Control' },
  { courseNumber: 'EL3082', courseName: 'Minor Project' },
  { courseNumber: 'EL4081', courseName: 'Project (Part-I)' },
  { courseNumber: 'EL4082', courseName: 'Project (Part-II)' },
  { courseNumber: 'EL4083', courseName: 'Practical Training' },
  { courseNumber: 'EL4084', courseName: 'Seminar' },
  { courseNumber: 'EL4086', courseName: 'General Viva Voce' },
  { courseNumber: 'HS1003', courseName: 'Professional Communication' },
  { courseNumber: 'HS1083', courseName: 'Language Lab' },
  { courseNumber: 'HS2002', courseName: 'Engineering Economics' },
  { courseNumber: 'HS2004', courseName: 'Public Finance' },
  { courseNumber: 'HS2006', courseName: 'International Economics' },
  { courseNumber: 'HS2081', courseName: 'Business Communication' },
  { courseNumber: 'HS3002', courseName: 'Organizational Behaviour' },
  { courseNumber: 'HS3003', courseName: 'Professional Ethics & Code of Conduct' },
  { courseNumber: 'HS3004', courseName: 'Human Resource Management' },
  { courseNumber: 'HS3006', courseName: 'Entrepreneurship' },
  { courseNumber: 'HS3008', courseName: 'Management Concepts & Practices' },
  { courseNumber: 'HS4003', courseName: 'Legal Issues & Requirement in Engineering' },
  { courseNumber: 'IT1002', courseName: 'Object Oriented Programming' },
  { courseNumber: 'IT2003', courseName: 'Web Technology' },
  { courseNumber: 'IT2092', courseName: 'Object Oriented Programming Lab' },
  { courseNumber: 'IT2093', courseName: 'Web Technology Lab' },
  { courseNumber: 'IT3001', courseName: 'Computer Networks' },
  { courseNumber: 'IT3002', courseName: 'Data Analytics' },
  { courseNumber: 'IT3003', courseName: 'Software Engineering' },
  { courseNumber: 'IT3004', courseName: 'Object Oriented System Design' },
  { courseNumber: 'IT3005', courseName: 'Cyber Security' },
  { courseNumber: 'IT3021', courseName: 'E-Commerce' },
  { courseNumber: 'IT3022', courseName: 'Cloud Computing' },
  { courseNumber: 'IT3023', courseName: 'Computer Vision' },
  { courseNumber: 'IT3024', courseName: 'Mobile Computing' },
  { courseNumber: 'IT3025', courseName: 'Enterprise Resource Planning' },
  { courseNumber: 'IT3026', courseName: 'Bio-informatics' },
  { courseNumber: 'IT3027', courseName: 'Multimedia Applications' },
  { courseNumber: 'IT3028', courseName: 'Information and Coding Theory' },
  { courseNumber: 'IT3029', courseName: 'Software Design and Validation' },
  { courseNumber: 'IT3030', courseName: 'Formal Verification: Theory and Practice' },
  { courseNumber: 'IT3032', courseName: 'Object Oriented Systems' },
  { courseNumber: 'IT4031', courseName: 'Information Retrieval' },
  { courseNumber: 'IT4033', courseName: 'Natural Language Processing' },
  { courseNumber: 'IT4035', courseName: 'Operation Research' },
  { courseNumber: 'IT4037', courseName: 'Data Mining and Data Warehousing' },
  { courseNumber: 'IT4039', courseName: 'Information Security' },
  { courseNumber: 'IT4021', courseName: 'Internet of Things' },
  { courseNumber: 'IT4022', courseName: 'Cyber Law and Intellectual Property Rights' },
  { courseNumber: 'IT4024', courseName: 'Computer Security' },
  { courseNumber: 'IT4026', courseName: 'Network Security' },
  { courseNumber: 'IT4027', courseName: 'Software Project Management' },
  { courseNumber: 'IT4028', courseName: 'Cyber Security' },
  { courseNumber: 'IT4029', courseName: 'Management Information System' },
  { courseNumber: 'MA1001', courseName: 'Mathematics – I' },
  { courseNumber: 'MA1002', courseName: 'Mathematics – II' },
  { courseNumber: 'MA2001', courseName: 'Mathematics – III' },
  { courseNumber: 'MA2002', courseName: 'Mathematics – IV' },
  { courseNumber: 'MA2003', courseName: 'Discrete Mathematics' },
  { courseNumber: 'MA2004', courseName: 'Numerical Methods' },
  { courseNumber: 'ME1001', courseName: 'Engineering Mechanics' },
  { courseNumber: 'ME1081', courseName: 'Basic Manufacturing Systems' },
  { courseNumber: 'ME2011', courseName: 'Thermodynamics and Hydraulics' },
  { courseNumber: 'ME2017', courseName: 'Thermodynamics & Fluid Mechanics' },
  { courseNumber: 'PH1003', courseName: 'Physics' },
  { courseNumber: 'PH1093', courseName: 'Physics Lab' },
  { courseNumber: 'TP3081', courseName: 'Cognitive Aptitude Test-I' },
  { courseNumber: 'TP3082', courseName: 'Cognitive Aptitude Test-II' }
];

// Helper function to find a course code by name (case insensitive)
export const findCourseByName = (name) => {
  if (!name) return null;
  
  const normalizedName = name.trim().toLowerCase();
  
  // First try for exact matches
  for (const course of courseMapping) {
    if (course.courseName.toLowerCase() === normalizedName) {
      return course;
    }
  }
  
  // Next try for contains matches
  for (const course of courseMapping) {
    if (course.courseName.toLowerCase().includes(normalizedName) || 
        normalizedName.includes(course.courseName.toLowerCase())) {
      return course;
    }
  }
  
  // If still no match, try with word boundaries
  const words = normalizedName.split(/\s+/);
  if (words.length > 1) {
    for (const course of courseMapping) {
      const courseNameLower = course.courseName.toLowerCase();
      // Check if all words are found in the course name
      if (words.every(word => courseNameLower.includes(word))) {
        return course;
      }
    }
  }
  
  return null;
};

// Helper function to find a course name by code (case insensitive)
export const findCourseByCode = (code) => {
  if (!code) return null;
  
  const normalizedCode = code.trim().toUpperCase();
  
  // First try exact match
  for (const course of courseMapping) {
    if (course.courseNumber.toUpperCase() === normalizedCode) {
      return course;
    }
  }
  
  // If no exact match, try prefix match (e.g. CS300 matches CS30002)
  if (normalizedCode.length >= 3) {
    for (const course of courseMapping) {
      if (course.courseNumber.toUpperCase().startsWith(normalizedCode)) {
        return course;
      }
    }
  }
  
  return null;
};
